name: intro-php #nom sans maj/charSpeciaux/espaces
recipe: lamp
config:
  php: '8.2'
  webroot: .
  xdebug: 'develop,debug'
services: 
  appserver: 
    config: 
      php: ./lando.config/php.ini
  database:
    portforward: 3307
    creds: 
      user: hanakhin
      password: lejedi9970
      database: intro_php 